### ISSUE TITLE
Relax dependency caps once fixed

### ISSUE THREAD

**Issue by dennisbader** [unit8co/darts#1772]
There are multiple issues from some of our depencies. We should relax the version caps again once the issues are fixed:

- [x] numpy<1.24.0 due to shap: track issues [here](https://github.com/slundberg/shap/pull/1890#issuecomment-1540767609) and [here](https://github.com/dsgibbons/shap/pull/7) (fixed with #1883)
- [x] holidays<0.25.0 due to prophet/holidays: track issues [here](https://github.com/facebook/prophet/issues/2430) and PR [here](https://github.com/facebook/prophet/pull/2431) (fixed with #1805)
- [x] catboost<1.2.0 due to catboost with cmake (fixed with #1589, catboost is now an optional dependency)

**Comment by dennisbader** [comment]
Update: Looks like shap is about to release a new version, see [here](https://github.com/slundberg/shap/pull/3058)

**Comment by thomasburgess** [comment]
catboost < 1.2 is really uncooperative with m1 macs, it sure would be nice to lift that cap!

**Comment by dennisbader** [comment]
I think we'll exclude catboost from our dependencies but continue to support the model with our wrapper. 
We then leave the installation to the user.

**Comment by dennisbader** [comment]
We just merged #1589, making Prophet, LightGBM, and CatBoost optional dependencies (they are excluded from the default `darts` dependencies).
Just tested installation and unit tests on my M1 device. Works like a charm :) 
This will be released tomorrow 🚀 

Closing the issue now.
